# Generated by Django 5.0.6 on 2024-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarantsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Item',
            field=models.TextField(default=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
